# Generated by Django 3.0.5 on 2020-04-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200410_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
